server: 
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/JJConfigManager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 090500
    driver-class-name: com.mysql.jdbc.Driver